name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Upload Files via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}        
        server-dir: /public_html     
        exclude: |
         vendor/
         .git*
         node_modules/
         '**/*.log'
                